package lightningrv

import chisel3._

/**
  * Decoded Instruction Command Bundle for Pipeline Decoupled Queues (64-Bit + 256-Bit Vector Enabled)
  */
class ExecuteCommand extends Bundle {
  val pc              = UInt(64.W)
  val inst            = UInt(32.W)
  val rd              = UInt(5.W)
  val rs1             = UInt(5.W)
  val rs2             = UInt(5.W)
  val funct3          = UInt(3.W)
  val useImm          = Bool()
  val imm             = UInt(64.W)
  val aluOp           = UInt(6.W)
  val isSlowLane      = Bool()
  val isFastLane      = Bool()
  val isMemLane       = Bool()
  val isVectorLane    = Bool()
  val isLoad          = Bool()
  val isStore         = Bool()
  val isVectorLoad    = Bool()
  val isVectorStore   = Bool()
  val isBranch        = Bool()
  val isJump          = Bool()
  val isJalr          = Bool()
  val isFence         = Bool()
  val predictedTaken  = Bool()
  val predictedTarget = UInt(64.W)
}

object ALUOp {
  val ADD   = 0.U(6.W)
  val SUB   = 1.U(6.W)
  val ADDI  = 2.U(6.W)
  val SLL   = 3.U(6.W)
  val SRL   = 4.U(6.W)
  val SRA   = 5.U(6.W)
  val SLT   = 6.U(6.W)
  val SLTU  = 7.U(6.W)
  val XOR   = 8.U(6.W)
  val OR    = 9.U(6.W)
  val AND   = 10.U(6.W)
  val LUI   = 11.U(6.W)
  val MUL   = 12.U(6.W)
  val MULH  = 13.U(6.W)
  val DIV   = 14.U(6.W)
  val REM   = 15.U(6.W)
  // Keshav-ISA Scalar Extensions
  val SADD  = 16.U(6.W)
  val MIN   = 17.U(6.W)
  val MAX   = 18.U(6.W)
  // RV64 Word Operations
  val ADDW  = 19.U(6.W)
  val SUBW  = 20.U(6.W)
  val SLLW  = 21.U(6.W)
  val SRLW  = 22.U(6.W)
  val SRAW  = 23.U(6.W)
  val MULW  = 24.U(6.W)
  val DIVW  = 25.U(6.W)
  val REMW  = 26.U(6.W)
  // Keshav-ISA 8-Wide SIMD Vector Operations (RV64V)
  val VADD  = 27.U(6.W)
  val VSUB  = 28.U(6.W)
  val VMUL  = 29.U(6.W)
  val VMIN  = 30.U(6.W)
  val VMAX  = 31.U(6.W)
  val VLE32 = 32.U(6.W)
  val VSE32 = 33.U(6.W)
}
